language: ruby
rvm:
- 2.2.2
before_install: gem install bundler -v 1.11.2
deploy:
  api_key:
    secure: rh1HenPk76uWAp74CQ1AA/Q9OqFY5LLyX78mvG1yF3uqZ+sT/4pVrJRxjeEbWUDXtFivNnApS++GPmcS/CmIUIvqQ6ylmXsqlf40/K8JGK3SCtJ2ZvUmHXkOwlB7K4j03hAX28e4mRkS/jHOEW0IZvQrnfosa4tZSsPQhD6QXEmGhxPxekigNbW31Y9WOAr28ykC9ASbD3X8dXF4x/BuLO+kcVyRHu5VA7ZUtw5s3Fuop9l0PZssUzai8v2ZO04PAKelTp1jpDaMm0ONN1Mv+7JfPpJ6s6NervvdnIBXRw6wB69SkNB5wdiDTA5b6oCXjFK9+9iqdJuSqM8AUVeBlpGU6LcZqpsPf7NcLejMWJg85pfKNg7zF9UBd/Yq+LFCDdUC9grouVZ1u9wn6b+6Rm1JCSkTQO8SS23igJiBQ/kAhOL8QmDbuxOnGUH4NAZTqcGio6uPpRqCk/M7rLY8Zxbwl1PM13RfzacOVFwGip2DzjyhMmNmn2r4YbEzvWkgIkGvPezVkyI3LfitlGuk6ikSoO8j3Pq+4MDjl/YlfyV8GTOvyrxkSQ/XOYPxA6tXwcTrnaPofOUN+XqJ/7Ik4sliX/A72kWnvK7TEfdClM0vPQCXCkHrOqnqzraakHWq9nqxcnQfwH9bIpOT8lgAX74/eU7K4t2v1QodF4DdtFQ=
  gem: service_logger
  on:
    tags: true
    repo: westfieldlabs/service_logger